export const PRODUCT_CATEGORIES = [
  'Beverages',
  'Coffee, Tea & Cocoa',
  'Snacks & Sweets',
  'Dairy & Eggs',
  'Bread & Bakery',
  'Canned Goods',
  'Instant Noodles & Soups',
  'Grains, Pasta & Noodles',
  'Condiments & Sauces',
  'Spices & Seasonings',
  'Cooking Oils & Essentials',
  'Breakfast & Cereal',
  'Frozen Foods',
  'Meat & Seafood',
  'Fresh Produce',
  'Personal Care',
  'Health & Wellness',
  'Household Supplies',
  'Cleaning & Laundry',
  'Baby Care',
  'Pet Supplies',
  'Stationery & School Supplies',
  'Hardware & DIY',
  'Cigarettes & Tobacco',
  'Alcohol & Spirits',
  'Electronics & Gadgets',
  'Others'
];
